## Activation Function

### Threshold Function 

In [1]:
li = [-1,1,2,'s']
type(li)

list

In [4]:
import numpy as np
x = np.array([-1,1,2])
type(x)

numpy.ndarray

In [5]:
x > 0

array([False,  True,  True])

In [6]:
(x > 0).astype(int)

array([0, 1, 1])

In [7]:
def threshold_function(x):
    y = x > 0
    return y.astype(int)

In [8]:
x = np.array([-1,1,2])
threshold_function(x)

array([0, 1, 1])

### Sigmoid Function

In [9]:
np.exp(1)

2.718281828459045

In [19]:
def sigmoid_function(x):
    return 1 / (1+np.exp(-x))

In [20]:
x = np.array([-1,1,2])
sigmoid_function(x)

array([0.26894142, 0.73105858, 0.88079708])

### Tengent Function

In [12]:
def tengent_function(x):
    return (1-np.exp(-2*x)) / (1+np.exp(-2*x))

x = np.array([-1,1,2])
tengent_function(x)

array([-0.76159416,  0.76159416,  0.96402758])

In [13]:
np.tanh(x)

array([-0.76159416,  0.76159416,  0.96402758])

### Relu Function

In [14]:
def relu_function(x):
    return np.maximum(0,x)

x = np.array([-1,1,2])
relu_function(x)

array([0, 1, 2])

## 神經網路建構過程

In [15]:
import numpy as np
X = np.array([1,2])
W = np.array([[1,3,5],[2,4,6]])
Y = np.dot(X,W)

In [16]:
Y

array([ 5, 11, 17])

In [17]:
network = {}
network['w1'] = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
network['b1'] = np.array([0.1,0.2,0.3])

network['w2'] = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
network['b2'] = np.array([0.1,0.2])

In [21]:
x = np.array([1,0.5])
a = np.dot(x, network['w1']) + network['b1']

z = sigmoid_function(a)
y = np.dot(z, network['w2']) + network['b2']

y

array([0.51615984, 1.21402696])

### Softmax Function

In [22]:
np.exp(1)

2.718281828459045

In [23]:
np.exp(-100)

3.720075976020836e-44

In [24]:
np.exp(100)

2.6881171418161356e+43

In [26]:
def softmax_function(x):
    return np.exp(x) / np.sum(np.exp(x))

X = np.array([-1,1,2])
softmax_function(X)

array([0.03511903, 0.25949646, 0.70538451])

In [27]:
network = {}
network['w1'] = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
network['b1'] = np.array([0.1,0.2,0.3])

network['w2'] = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
network['b2'] = np.array([0.1,0.2])

In [28]:
x = np.array([1,0.5])
a = np.dot(x, network['w1']) + network['b1']

z = sigmoid_function(a)
y = np.dot(z, network['w2']) + network['b2']

y

array([0.51615984, 1.21402696])

In [29]:
softmax_function(y)

array([0.33228528, 0.66771472])