## 安裝TensorFlow

In [1]:
! pip install tensorflow

  Running setup.py bdist_wheel for termcolor: started
  Running setup.py bdist_wheel for termcolor: finished with status 'done'
  Stored in directory: C:\Users\USER\AppData\Local\pip\Cache\wheels\7c\06\54\bc84598ba1daf8f970247f550b175aaaee85f68b4b0c5ab2c6
  Running setup.py bdist_wheel for gast: started
  Running setup.py bdist_wheel for gast: finished with status 'done'
  Stored in directory: C:\Users\USER\AppData\Local\pip\Cache\wheels\9a\1f\0e\3cde98113222b853e98fc0a8e9924480a3e25f1b4008cedb4f
  Running setup.py bdist_wheel for absl-py: started
  Running setup.py bdist_wheel for absl-py: finished with status 'done'
  Stored in directory: C:\Users\USER\AppData\Local\pip\Cache\wheels\a0\f8\e9\1933dbb3447ea6ef57062fd5461cb118deb8c2ed074e8344bf
Successfully built termcolor gast absl-py


distributed 1.21.8 requires msgpack, which is not installed.


In [2]:
import tensorflow as tf

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


## 常數 (Constant)

In [3]:
hello = tf.constant('Hello World')
hello

<tf.Tensor 'Const:0' shape=() dtype=string>

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

## 會話 (Session)

In [6]:
s = tf.Session()
s

In [7]:
type(s)

tensorflow.python.client.session.Session

In [8]:
s.run(hello)

b'Hello World'

In [9]:
a = s.run(hello)

In [11]:
a

b'Hello World'

In [10]:
type(a)

bytes

## Tensorflow Basic

### 常數

In [12]:
x  = tf.constant(100)

In [16]:
x

<tf.Tensor 'Const_1:0' shape=() dtype=int32>

In [13]:
type(x)

tensorflow.python.framework.ops.Tensor

### 會話 (Session)

In [14]:
sess = tf.Session()
sess.run(x)

100

In [15]:
type(sess)

tensorflow.python.client.session.Session

In [17]:
y = sess.run(x)

In [18]:
y

100

In [19]:
type(y)

numpy.int32

In [24]:
sess.close()

### Operation (操作)

In [20]:
x = tf.constant(2)
y = tf.constant(3)

In [21]:
x

<tf.Tensor 'Const_2:0' shape=() dtype=int32>

In [22]:
y

<tf.Tensor 'Const_3:0' shape=() dtype=int32>

In [23]:
x + y

<tf.Tensor 'add:0' shape=() dtype=int32>

In [28]:
with tf.Session() as sess:
    print(sess.run(x + y))
    print(sess.run(x - y))
    print(sess.run(x * y))
    print(sess.run(x / y))

5
-1
6
0.6666666666666666


### Placeholder 

In [29]:
x = tf.placeholder(tf.int32)
y = tf.placeholder(tf.int32)

In [30]:
x

<tf.Tensor 'Placeholder:0' shape=<unknown> dtype=int32>

In [31]:
type(x)

tensorflow.python.framework.ops.Tensor

### 定義操作 

In [37]:
add = tf.add(x,y)
sub = tf.subtract(x,y)
mul = tf.multiply(x,y)
div = tf.divide(x,y)

In [38]:
with tf.Session() as sess:
    print(sess.run(add, feed_dict={x:20, y:30}))
    print(sess.run(sub, feed_dict={x:20, y:30}))
    print(sess.run(mul, feed_dict={x:20, y:30}))
    print(sess.run(div, feed_dict={x:20, y:30}))

50
-10
600
0.6666666666666666


In [39]:
with tf.Session() as sess:
    x = sess.run(add, feed_dict={x:20, y:30})

In [40]:
x

50

In [41]:
type(x)

numpy.int32

### 矩陣操作

In [44]:
import numpy as np
a = np.array([[5.0,5.0]])
b = np.array([[2.0],[2.0]])

In [45]:
a

array([[5., 5.]])

In [47]:
a.shape

(1, 2)

In [46]:
b

array([[2.],
       [2.]])

In [48]:
b.shape

(2, 1)

In [50]:
mat1 = tf.constant(a)
mat2 = tf.constant(b)

In [51]:
matrix_multi = tf.matmul(mat1,mat2)

In [52]:
with tf.Session() as sess:
    x = sess.run(matrix_multi)

In [53]:
x

array([[20.]])