## 激活函数

### threshold function

In [2]:
import numpy as np
def threshold_function(x):
    y = x > 0
    return y.astype(int)

x = np.array([-1,1,2])
threshold_function(x)

array([0, 1, 1])

### sigmoid function

In [3]:
def sigmoid_function(x):
    return 1/ (1 + np.exp(-x))

x = np.array([-1,1,2])
sigmoid_function(x)

array([0.26894142, 0.73105858, 0.88079708])

### tangent function

In [13]:
def tangent_function(x):
    return (1 - np.exp(-2*x)) / (1 + np.exp(-2*x))

x = np.array([-1,1,2])
tangent_function(x)


array([-0.76159416,  0.76159416,  0.96402758])

In [14]:
np.tanh(x)

array([-0.76159416,  0.76159416,  0.96402758])

### relu function

In [6]:
def relu_function(x):
    return np.maximum(0,x)

x = np.array([-1,1,2])
relu_function(x)


array([0, 1, 2])

## 单层神经网络前向传播过程

In [15]:
import numpy as np
X = np.array([1,2])
W = np.array([[1,3,5],[2,4,6]])
Y = np.dot(X,W)
Y

array([ 5, 11, 17])

## 两层神经网络前向传播过程

In [16]:
network = {}
network['w1'] = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
network['b1'] = np.array([0.1,0.2,0.3])
network['w2'] = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
network['b2'] = np.array([0.1,0.2])

In [22]:
x = np.array([1,0.5])
x.shape
network['w1'].shape
a1 = np.dot(x, network['w1']) + network['b1']
a1.shape
z1 = sigmoid_function(a1)
z1
y = np.dot(z1, network['w2']) + network['b2']
y

array([0.51615984, 1.21402696])

## Softmax

In [23]:
def softmax_function(x):
    return np.exp(x) / np.sum(np.exp(x))

softmax_function(y)

array([0.33228528, 0.66771472])

In [24]:
np.sum(softmax_function(y))

1.0