## 建立 CNN

In [16]:
# Importing the Keras libraries and packages
from keras.models import Sequential 
from keras.layers import Conv2D
from keras.layers import MaxPooling2D 
from keras.layers import Flatten
from keras.layers import Dense

# Initialising the CNN
classifier = Sequential()

In [2]:
?Conv2D

In [17]:
# 1. Convolution
classifier.add(Conv2D(32, (3, 3), input_shape = (64, 64,
3), activation = 'relu'))

In [18]:
# 2. Max Pooling
classifier.add(MaxPooling2D(pool_size = (2, 2)))

In [19]:
# Adding a second convolutional layer
classifier.add(Conv2D(32, (3, 3), activation = 'relu'))
classifier.add(MaxPooling2D(pool_size = (2, 2)))

In [20]:
# 3. Flattening
classifier.add(Flatten())

In [21]:
# 4. Fully Connection
classifier.add(Dense(units = 128, activation = 'relu')) 
classifier.add(Dense(units = 1, activation = 'sigmoid'))

In [22]:
classifier.compile(optimizer = 'adam', loss =
'binary_crossentropy', metrics = ['accuracy'])

In [8]:
from keras.preprocessing.image import ImageDataGenerator
?ImageDataGenerator

In [23]:
train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2, horizontal_flip = True)

In [24]:
test_datagen = ImageDataGenerator(rescale = 1./255)

In [25]:
training_set = train_datagen.flow_from_directory(
    'dataset/training_set', target_size = (64, 64),
     batch_size = 32,
     class_mode = 'binary')

Found 8000 images belonging to 2 classes.


In [24]:
! pip install Pillow

In [26]:
from PIL import Image

In [27]:
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

test_set = test_datagen.flow_from_directory(
    'dataset/test_set', target_size = (64, 64),
    batch_size = 32, 
    class_mode = 'binary')
               

Found 2000 images belonging to 2 classes.


## 餵資料進模型

In [28]:
from PIL import Image
classifier.fit_generator(training_set, steps_per_epoch = 8000,
epochs = 1, validation_data = test_set, validation_steps = 2000)
          

Epoch 1/1
8000/8000 [==============================] - 4253s 532ms/step - loss: 0.3943 - acc: 0.8128 - val_loss: 0.4803 - val_acc: 0.8102


## 預測單張圖片的類別

In [68]:
import numpy as np
from keras.preprocessing import image
test_image = image.load_img('dataset/single_prediction/cat_or_dog_1.jpg', target_size= (64,64))
test_image = image.img_to_array(test_image)

type(test_image)


numpy.ndarray

In [69]:
test_image.shape

(64, 64, 3)

In [70]:
test_image = np.expand_dims(test_image, axis = 0)

In [71]:
test_image.shape

(1, 64, 64, 3)

In [79]:
result = classifier.predict_classes(test_image)

In [80]:
result

array([[1]], dtype=int32)

## Np.expand_dims

In [76]:
a = np.array([1,2,3])
print(a)
b = np.expand_dims(a, axis=0)
print(b)

[1 2 3]
[[1 2 3]]
